### ISSUE TITLE
Difference between real_needle and needle in needle.jsonl?

### ISSUE THREAD

**Issue by zhongmz** [nightdessert/Retrieval_Head#3]
Will the choice of needle cause different observational phenomena? What is the difference between these two needles in https://github.com/nightdessert/Retrieval_Head/blob/f59125cb8a14bded517162fb954f1b5c57dc76f4/haystack_for_detect/needles.jsonl#L1?

**Comment by nightdessert** [comment]
> Will the choice of needle cause different observational phenomena? What is the difference between these two needles in
> 
> https://github.com/nightdessert/Retrieval_Head/blob/f59125cb8a14bded517162fb954f1b5c57dc76f4/haystack_for_detect/needles.jsonl#L1
> 
> ?

1. Maybe an LLM is not good at retrieving some sets of (needle, haystack) making the final retrieval scores smaller.
2. 'Real needle' is the most important tokens in the needle, and we expect model to recall them. We specially define real needle to reduce the variance of the final retrieval score caused by different expression by generation. For example if the needle is 'The best thing to do in a is xxx', and the question is "What is the best thing to do in a",then the real needle is 'xxx'. Because model may answer something like 'in a the best thing is xxx', 'xxx' or even 'Glad to answer this question, according the the passage, the answer to the question is xxx'. So, only use   'xxx' as the gold answer to calculate recall is a clean choice

**Comment by nightdessert** [comment]
> Will the choice of needle cause different observational phenomena? What is the difference between these two needles in
> 
> https://github.com/nightdessert/Retrieval_Head/blob/f59125cb8a14bded517162fb954f1b5c57dc76f4/haystack_for_detect/needles.jsonl#L1
> 
> ?

Thanks for this question, I have clarified this question in readme.

**Comment by zhongmz** [comment]
Thanks for your clear reply.
