### ISSUE TITLE
About data for  haystack_for_detect

### ISSUE THREAD

**Issue by kenoharada** [nightdessert/Retrieval_Head#4]
Thank you for sharing your work!

I have several questions.

- How data was created for haystack_for_detect
Is there any script to reproduce p1.txt of part1/part2/part3? or what is the source of these text?

- p1.txt seems have not text data, is that correct data?
https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/haystack_for_detect/part1/p1.txt#L1

but you read file as it is
https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/retrieval_head_detection.py#L449-L452
https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/retrieval_head_detection.py#L494

**Comment by nightdessert** [comment]
> Thank you for sharing your work!
> 
> I have several questions.
> 
> * How data was created for haystack_for_detect
>   Is there any script to reproduce p1.txt of part1/part2/part3? or what is the source of these text?
> * p1.txt seems have not text data, is that correct data?
>   https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/haystack_for_detect/part1/p1.txt#L1
> 
> but you read file as it is
> 
> https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/retrieval_head_detection.py#L449-L452
> 
> 
> https://github.com/nightdessert/Retrieval_Head/blob/2d9fb9d72eaa685acf6a4d29d0115a682c3c05ab/retrieval_head_detection.py#L494

Glad to answer your question.
1. How data was created:   Haystacks are made from concatenating arbitrary documents, which I crawled from slimpajama, into a long enough document. And the needles are made up by myself.  For creating needle in the haystack data, we only need to make sure that the question is ambiguous or can also be answered from the 'haystack'.
2. p1.txt seems have not text data, is that correct data:  I select this json style sample deliberately since needle in the haystack should be performed regardless of the domain of the haystack

**Comment by kenoharada** [comment]
Thank you very much!
